### ISSUE TITLE
Missing default Berkshelf API server

### ISSUE THREAD

**Issue by jaalfaro** [ngageoint/geoq-chef-installer#4]
I've been following the instructions on a OS X, and get through the point where the VM is build for for virtualbox.  However when we start performing the cookbook steps, we get:

```
Updating Vagrant's berkshelf: '/Users/#####/.berkshelf/default/vagrant/berkshelf-20140519-55555-57voal-default'
Resolving cookbook dependencies...
Fetching 'geoq' from source at cookbooks/geoq
Berkshelf::NoAPISourcesDefined: Your Berksfile does not define any API sources! You must define at least one source in order to download cookbooks. To add the default Berkshelf API server, add the following code to the top of your Berksfile:

    source 'https://api.berkshelf.com'
```

Other than the default provided, do you have a different recomendation for this to work?  

Thanks

**Comment by jaycrossler** [comment]
Updated to have that default server (required for updated version of Berkshelf)
